# Generated by Django 3.2 on 2021-05-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veikla',
            name='pajamos',
            field=models.FloatField(max_length=100),
        ),
    ]
