# Generated by Django 3.2 on 2021-05-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes_app', '0002_alter_veikla_pajamos'),
    ]

    operations = [
        migrations.AddField(
            model_name='veikla',
            name='islaidos',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
