# Generated by Django 3.2 on 2021-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes_app', '0004_veikla_islaidos_30'),
    ]

    operations = [
        migrations.AddField(
            model_name='veikla',
            name='pencija_2_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veikla',
            name='pencija_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='veikla',
            name='islaidos_30',
            field=models.BooleanField(default=False),
        ),
    ]
