# Generated by Django 3.2 on 2021-05-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes_app', '0005_auto_20210506_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veikla',
            name='pencija_2_4',
        ),
        migrations.RemoveField(
            model_name='veikla',
            name='pencija_3',
        ),
        migrations.AddField(
            model_name='veikla',
            name='status',
            field=models.CharField(blank=True, choices=[('p24', 'Pensija 2.4%'), ('p3', 'Pensija 3%'), ('pn', 'Nekaupiama')], default='pn', help_text='Ar kaupiate pensija?', max_length=3),
        ),
    ]
