# Generated by Django 3.2 on 2021-05-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes_app', '0007_alter_veikla_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veikla',
            name='islaidos',
        ),
        migrations.RemoveField(
            model_name='veikla',
            name='pajamos',
        ),
    ]
