# Generated by Django 3.2 on 2021-05-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxes_app', '0009_uzdarbis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzdarbis',
            name='darbas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzdarbiai', to='taxes_app.veikla'),
        ),
    ]
