# Generated by Django 3.2 on 2021-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes_app', '0013_auto_20210511_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzdarbis',
            name='islaidos',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uzdarbis',
            name='pajamos',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
