# Generated by Django 3.2 on 2021-05-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes_app', '0014_auto_20210511_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzdarbis',
            name='islaidos',
            field=models.FloatField(default=0, max_length=100, null=True),
        ),
    ]
