# Generated by Django 3.2 on 2021-05-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes_app', '0015_alter_uzdarbis_islaidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veikla',
            name='islaidos_30',
        ),
        migrations.AddField(
            model_name='veikla',
            name='status2',
            field=models.CharField(choices=[('i30', 'Išlaidos 30%'), ('if', 'Faktinės išlaidos')], default='if', help_text='Pasirinkite išlaidas', max_length=3),
        ),
    ]
