# Generated by Django 3.2 on 2021-05-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes_app', '0016_auto_20210515_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veikla',
            name='status2',
            field=models.CharField(choices=[('isl30', 'Išlaidos 30%'), ('islf', 'Faktinės išlaidos')], default='if', help_text='Pasirinkite išlaidas', max_length=5),
        ),
    ]
