# Generated by Django 3.2 on 2021-05-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes_app', '0019_auto_20210515_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='veikla',
            name='pajamos',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='veikla',
            name='status3',
            field=models.CharField(choices=[('y', 'Taip'), ('n', 'Ne')], default='n', help_text='Ar norite pasinaudoti sodros mokesčių lengvata?', max_length=1),
        ),
    ]
