# Generated by Django 3.2 on 2021-05-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes_app', '0021_veikla_islaidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veikla',
            name='islaidos',
        ),
        migrations.RemoveField(
            model_name='veikla',
            name='pajamos',
        ),
    ]
