# Generated by Django 3.2 on 2021-05-25 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxes_app', '0022_auto_20210520_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veikla',
            name='asmuo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiklos', to=settings.AUTH_USER_MODEL),
        ),
    ]
